/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kashuo_kcp_plus_NativeJavaUtil */

#ifndef _Included_com_kashuo_kcp_plus_NativeJavaUtil
#define _Included_com_kashuo_kcp_plus_NativeJavaUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kashuo_kcp_plus_NativeJavaUtil
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kashuo_kcp_plus_NativeJavaUtil_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     com_kashuo_kcp_plus_NativeJavaUtil
 * Method:    decodeCommand
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kashuo_kcp_plus_NativeJavaUtil_decodeCommand
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_kashuo_kcp_plus_NativeJavaUtil
 * Method:    encodeCommand
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kashuo_kcp_plus_NativeJavaUtil_encodeCommand
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
